-- Jalankan seluruh berkas ini di Supabase Dashboard > SQL Editor.
-- Aman dijalankan berulang kali.

/* ── Tabel agenda ─────────────────────────────────────────────────────────
   Kolom tanggal sengaja bertipe text, bukan date, supaya bisa diisi rentang
   seperti "15-28 Juni 2026" atau keterangan seperti "Menyusul". */
create table if not exists public.agenda (
  id bigint generated by default as identity primary key,
  tanggal text not null,
  judul text not null,
  deskripsi text,
  urutan integer not null default 0
);

create table if not exists public.faq (
  id bigint generated by default as identity primary key,
  pertanyaan text not null,
  jawaban text not null,
  urutan integer not null default 0
);

create index if not exists agenda_urutan_idx on public.agenda(urutan);
create index if not exists faq_urutan_idx on public.faq(urutan);

alter table public.agenda enable row level security;
alter table public.faq enable row level security;

drop policy if exists "publik baca agenda" on public.agenda;
drop policy if exists "admin kelola agenda" on public.agenda;
drop policy if exists "publik baca faq" on public.faq;
drop policy if exists "admin kelola faq" on public.faq;

create policy "publik baca agenda" on public.agenda for select to anon,authenticated using(true);
create policy "admin kelola agenda" on public.agenda for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca faq" on public.faq for select to anon,authenticated using(true);
create policy "admin kelola faq" on public.faq for all to authenticated using(public.is_admin()) with check(public.is_admin());

/* Isi awal disalin dari teks yang selama ini tertulis tetap di beranda.
   Hanya dijalankan bila tabelnya masih kosong, sehingga menjalankan ulang
   berkas ini tidak menggandakan data yang sudah kamu sunting. */
insert into public.agenda (tanggal, judul, deskripsi, urutan)
select * from (values
  ('15 Jun 2026','Pembukaan PPDB 2026/2027','Pendaftaran jalur prestasi & reguler resmi dibuka.',1),
  ('28 Jun 2026','Tes Seleksi Calon Siswa','Tes akademik dan wawancara peserta didik baru.',2),
  ('10 Jul 2026','Pengumuman Hasil Seleksi','Pengumuman & daftar ulang siswa yang diterima.',3),
  ('15 Jul 2026','Masa Pengenalan Sekolah','MPLS bagi siswa baru tahun ajaran 2026/2027.',4)
) as v(tanggal,judul,deskripsi,urutan)
where not exists (select 1 from public.agenda);

insert into public.faq (pertanyaan, jawaban, urutan)
select * from (values
  ('Kapan pendaftaran PPDB dibuka?','PPDB tahun ajaran 2026/2027 dibuka mulai 15 Juni 2026 melalui jalur prestasi, reguler, dan beasiswa.',1),
  ('Apa saja peminatan yang tersedia?','Saat ini tersedia peminatan IPS (Ilmu Pengetahuan Sosial) dengan pendampingan intensif menuju PTN.',2),
  ('Apakah ada program keagamaan?','Ya. Pembiasaan shalat dhuha, tahfiz Al-Quran, dan kajian rutin menjadi bagian keseharian siswa.',3),
  ('Bagaimana cara menghubungi sekolah?','Anda dapat menghubungi kami melalui telepon, email, atau mengisi formulir pada halaman Kontak.',4)
) as v(pertanyaan,jawaban,urutan)
where not exists (select 1 from public.faq);

/* ── Tautan media sosial ──────────────────────────────────────────────────
   Footer membaca empat kunci ini. Biarkan kosong bila akunnya belum ada;
   tautan yang kosong otomatis disembunyikan, tidak lagi mengarah ke '#'. */
insert into public.pengaturan (kunci, nilai) values
  ('instagram',''),
  ('youtube',''),
  ('tiktok',''),
  ('facebook','')
on conflict (kunci) do nothing;
