-- Jalankan seluruh file ini melalui Supabase Dashboard > SQL Editor.
--
-- AMAN DIJALANKAN BERULANG KALI. Seluruh data contoh di bagian bawah hanya
-- masuk bila tabelnya masih benar-benar kosong, dan baris `pengaturan` tidak
-- pernah menimpa nilai yang sudah ada. Menjalankan ulang berkas ini tidak
-- akan mengubah data sekolah yang sudah disunting lewat panel admin.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null default 'Pengguna',
  role text not null default 'viewer' check (role in ('admin','viewer')),
  created_at timestamptz not null default now()
);
create table if not exists public.pengaturan (id bigint generated by default as identity primary key,kunci text not null unique,nilai text not null);
create table if not exists public.berita (id bigint generated by default as identity primary key,judul text not null,slug text not null unique,kategori text not null,isi text not null,gambar text,tanggal date not null default current_date,dilihat integer not null default 0);
create table if not exists public.guru (id bigint generated by default as identity primary key,nama text not null,jabatan text not null,mapel text,foto text,urutan integer not null default 0);
create table if not exists public.ekstrakurikuler (id bigint generated by default as identity primary key,nama text not null,kategori text not null,deskripsi text not null,pembina text,jadwal text);
create table if not exists public.kategori_ekskul (id bigint generated by default as identity primary key,nama text not null unique,urutan integer not null default 0);
create table if not exists public.visi_misi (id bigint generated by default as identity primary key,tipe text not null check (tipe in ('visi','misi','tujuan','nilai')),judul text,isi text not null,urutan integer not null default 0);
create table if not exists public.tentang (id bigint generated by default as identity primary key,bagian text not null check (bagian in ('sejarah','sambutan','fasilitas')),judul text,isi text not null);
create table if not exists public.ppdb_info (id bigint generated by default as identity primary key,bagian text not null check (bagian in ('syarat','jadwal','alur','lokasi','faq')),judul text,isi text not null,tanggal text,file_formulir text,urutan integer not null default 0);
create table if not exists public.pesan_kontak (id bigint generated by default as identity primary key,nama text not null,email text not null,telepon text,subjek text,pesan text not null,tanggal timestamptz not null default now(),dibaca boolean not null default false);
create table if not exists public.audit_log (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete set null,action text not null,table_name text,record_id bigint,ip_address inet,created_at timestamptz not null default now());

-- Alamat IP pengirim pesan kontak. Dipakai sebagai pembatas laju kedua di
-- submit_contact_message(); tanpa ini batas per-email bisa dilewati cukup
-- dengan mengganti alamat email pada tiap kiriman.
alter table public.pesan_kontak add column if not exists ip text;

create index if not exists berita_tanggal_idx on public.berita(tanggal desc);
create index if not exists guru_urutan_idx on public.guru(urutan);
create index if not exists pesan_tanggal_idx on public.pesan_kontak(tanggal desc);

-- search_path sengaja dikosongkan pada seluruh fungsi SECURITY DEFINER.
-- Dengan begitu nama tabel tidak bisa dibajak lewat skema lain, dan setiap
-- rujukan wajib ditulis lengkap (public.x / auth.x / pg_catalog.x).
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,nama) values(new.id,coalesce(new.raw_user_meta_data->>'nama',pg_catalog.split_part(new.email,'@',1))) on conflict(id) do nothing;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;

alter table public.profiles enable row level security;
alter table public.pengaturan enable row level security;
alter table public.berita enable row level security;
alter table public.guru enable row level security;
alter table public.ekstrakurikuler enable row level security;
alter table public.kategori_ekskul enable row level security;
alter table public.visi_misi enable row level security;
alter table public.tentang enable row level security;
alter table public.ppdb_info enable row level security;
alter table public.pesan_kontak enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "profile sendiri" on public.profiles;
drop policy if exists "admin kelola profile" on public.profiles;
drop policy if exists "publik baca pengaturan" on public.pengaturan;
drop policy if exists "admin kelola pengaturan" on public.pengaturan;
drop policy if exists "publik baca berita" on public.berita;
drop policy if exists "admin kelola berita" on public.berita;
drop policy if exists "publik baca guru" on public.guru;
drop policy if exists "admin kelola guru" on public.guru;
drop policy if exists "publik baca ekskul" on public.ekstrakurikuler;
drop policy if exists "admin kelola ekskul" on public.ekstrakurikuler;
drop policy if exists "publik baca kategori ekskul" on public.kategori_ekskul;
drop policy if exists "admin kelola kategori ekskul" on public.kategori_ekskul;
drop policy if exists "publik baca visi misi" on public.visi_misi;
drop policy if exists "admin kelola visi misi" on public.visi_misi;
drop policy if exists "publik baca tentang" on public.tentang;
drop policy if exists "admin kelola tentang" on public.tentang;
drop policy if exists "publik baca ppdb" on public.ppdb_info;
drop policy if exists "admin kelola ppdb" on public.ppdb_info;
drop policy if exists "admin kelola pesan" on public.pesan_kontak;
drop policy if exists "admin baca audit" on public.audit_log;
drop policy if exists "admin tambah audit" on public.audit_log;

create policy "profile sendiri" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy "admin kelola profile" on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca pengaturan" on public.pengaturan for select to anon,authenticated using(true);
create policy "admin kelola pengaturan" on public.pengaturan for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca berita" on public.berita for select to anon,authenticated using(true);
create policy "admin kelola berita" on public.berita for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca guru" on public.guru for select to anon,authenticated using(true);
create policy "admin kelola guru" on public.guru for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca ekskul" on public.ekstrakurikuler for select to anon,authenticated using(true);
create policy "admin kelola ekskul" on public.ekstrakurikuler for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca kategori ekskul" on public.kategori_ekskul for select to anon,authenticated using(true);
create policy "admin kelola kategori ekskul" on public.kategori_ekskul for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca visi misi" on public.visi_misi for select to anon,authenticated using(true);
create policy "admin kelola visi misi" on public.visi_misi for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca tentang" on public.tentang for select to anon,authenticated using(true);
create policy "admin kelola tentang" on public.tentang for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca ppdb" on public.ppdb_info for select to anon,authenticated using(true);
create policy "admin kelola ppdb" on public.ppdb_info for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin kelola pesan" on public.pesan_kontak for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin baca audit" on public.audit_log for select to authenticated using(public.is_admin());
create policy "admin tambah audit" on public.audit_log for insert to authenticated with check(public.is_admin());

-- Pengunjung tidak boleh insert langsung ke tabel pesan. Semua pesan publik
-- melewati fungsi tervalidasi dan rate-limited di bawah ini.
drop policy if exists "publik kirim pesan" on public.pesan_kontak;
create index if not exists pesan_email_tanggal_idx on public.pesan_kontak(lower(email),tanggal desc);
create index if not exists pesan_ip_tanggal_idx on public.pesan_kontak(ip,tanggal desc);

-- Versi lama fungsi ini hanya menerima lima argumen. Harus dibuang lebih
-- dulu: kalau dibiarkan, panggilan berargumen lima jadi ambigu karena versi
-- baru punya p_ip bernilai bawaan null.
drop function if exists public.submit_contact_message(text,text,text,text,text);

create or replace function public.submit_contact_message(p_nama text,p_email text,p_telepon text default null,p_subjek text default null,p_pesan text default null,p_ip text default null) returns void language plpgsql security definer set search_path='' as $$
declare
  v_email text:=lower(trim(coalesce(p_email,'')));
  v_nama text:=trim(coalesce(p_nama,''));
  v_pesan text:=trim(coalesce(p_pesan,''));
  v_ip text:=nullif(trim(coalesce(p_ip,'')),'');
begin
  if char_length(v_nama) not between 2 and 100 or char_length(v_email)>254 or v_email !~ '^[A-Za-z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$' or char_length(coalesce(p_telepon,''))>30 or char_length(coalesce(p_subjek,''))>100 or char_length(v_pesan) not between 10 and 3000 then raise exception 'CONTACT_INVALID';end if;

  -- Urutan penguncian selalu email dulu, baru IP, supaya dua permintaan
  -- yang bersamaan tidak pernah saling mengunci (deadlock).
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_email,0));
  if v_ip is not null then perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('ip:'||v_ip,0));end if;

  if (select count(*) from public.pesan_kontak where lower(email)=v_email and tanggal>pg_catalog.now()-interval '15 minutes')>=3 then raise exception 'CONTACT_RATE_LIMITED';end if;
  if exists(select 1 from public.pesan_kontak where lower(email)=v_email and lower(trim(pesan))=lower(v_pesan) and tanggal>pg_catalog.now()-interval '1 hour') then raise exception 'CONTACT_RATE_LIMITED';end if;
  if v_ip is not null and (select count(*) from public.pesan_kontak where ip=v_ip and tanggal>pg_catalog.now()-interval '1 hour')>=8 then raise exception 'CONTACT_RATE_LIMITED';end if;

  insert into public.pesan_kontak(nama,email,telepon,subjek,pesan,ip) values(v_nama,v_email,nullif(trim(coalesce(p_telepon,'')),''),nullif(trim(coalesce(p_subjek,'')),''),v_pesan,v_ip);
end$$;
revoke all on function public.submit_contact_message(text,text,text,text,text,text) from public;
grant execute on function public.submit_contact_message(text,text,text,text,text,text) to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=excluded.public;
drop policy if exists "publik baca media" on storage.objects;
drop policy if exists "admin unggah media" on storage.objects;
drop policy if exists "admin ubah media" on storage.objects;
drop policy if exists "admin hapus media" on storage.objects;
create policy "publik baca media" on storage.objects for select to anon,authenticated using(bucket_id='media');
create policy "admin unggah media" on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_admin());
create policy "admin ubah media" on storage.objects for update to authenticated using(bucket_id='media' and public.is_admin()) with check(bucket_id='media' and public.is_admin());
create policy "admin hapus media" on storage.objects for delete to authenticated using(bucket_id='media' and public.is_admin());

-- =============================================================
-- DATA CONTOH
--
-- Semuanya dijaga supaya tidak pernah menimpa isian sungguhan. `pengaturan`
-- memakai DO NOTHING (dulu DO UPDATE, yang membuat alamat, telepon, email,
-- dan akreditasi sekolah kembali ke nilai contoh setiap kali berkas ini
-- dijalankan ulang). Tabel lain hanya diisi bila masih kosong.
-- =============================================================
insert into public.pengaturan(kunci,nilai) values
('nama_sekolah','SMA Putra Persada Batam'),('tagline','Unggul & Berakhlak'),('akreditasi','B'),('label_akreditasi','Akreditasi'),('peserta_didik','750+'),('label_peserta','Peserta Didik'),('pengajar','45+'),('label_pengajar','Pengajar'),('alamat','Jl. Raya Persada, Batam Center, Kota Batam, Kepulauan Riau'),('telepon','(0778) XXX-XXXX'),('email','info@smaputrapersada.sch.id'),('jam_operasional','Senin–Jumat, 07.00–15.00 WIB'),('ppdb_status','buka') on conflict(kunci) do nothing;

insert into public.berita(judul,slug,kategori,isi,tanggal,dilihat)
select * from (values
  ('Siswa Raih Emas Olimpiade Sains Provinsi Kepri','osn-emas','Prestasi','<p>Alhamdulillah, SMA Putra Persada Batam kembali meraih prestasi membanggakan.</p>','2026-06-12'::date,245),
  ('Pentas Seni & Perpisahan Kelas XII Berlangsung Meriah','pentas-seni','Kegiatan','<p>Suasana haru bercampur bahagia menyelimuti acara pentas seni dan perpisahan kelas XII.</p>','2026-06-08'::date,189),
  ('Shalat Dhuha & Tahfiz Rutin Setiap Pagi','shalat-dhuha','Keagamaan','<p>Pembinaan karakter islami dilakukan melalui shalat dhuha berjamaah dan tahfiz.</p>','2026-06-03'::date,156)
) as v(judul,slug,kategori,isi,tanggal,dilihat)
where not exists (select 1 from public.berita)
on conflict(slug) do nothing;

insert into public.guru(nama,jabatan,mapel,foto,urutan)
select * from (values
  ('Budi Santoso, M.Pd.','Kepala Sekolah','Manajemen Pendidikan','/assets/img/guru1.jpeg',1),
  ('Siti Aminah, S.Pd.','Guru Matematika','Matematika','/assets/img/guru2.jpeg',2),
  ('Ahmad Fauzi, M.Pd.','Guru Fisika','Fisika','/assets/img/guru3.jpeg',3),
  ('Maya Kartika, S.Pd.','Guru Bahasa Inggris','Bahasa Inggris','/assets/img/guru4.jpeg',4)
) as v(nama,jabatan,mapel,foto,urutan)
where not exists (select 1 from public.guru);

insert into public.visi_misi(tipe,judul,isi,urutan)
select * from (values
  ('visi',null::text,'Mewujudkan generasi yang cerdas, berkarakter, beriman, dan berdaya saing global.',1),
  ('misi',null::text,'Menyelenggarakan pembelajaran aktif, kreatif, dan berkualitas berbasis Kurikulum Merdeka.',1),
  ('misi',null::text,'Membina karakter islami melalui pembiasaan ibadah, tahfiz, dan keteladanan akhlak mulia.',2),
  ('nilai','Integritas','Menjunjung kejujuran dan tanggung jawab dalam segala hal.',1),
  ('nilai','Peduli','Menumbuhkan empati terhadap sesama dan lingkungan.',2)
) as v(tipe,judul,isi,urutan)
where not exists (select 1 from public.visi_misi);
