import { OriginalBanner, OriginalCta } from "@/components/original-sections";
import { getActivities } from "@/lib/data";

export const metadata = { title: "Ekstrakurikuler" };
const meta: Record<string, [string, string]> = { Olahraga: ["⚽", "from-leaf to-pine"], Seni: ["🎨", "from-amber-500 to-brass"], Akademik: ["📚", "from-teal-600 to-pine"], Keagamaan: ["🕌", "from-emerald-600 to-pine"] };

export default async function ActivitiesPage() {
  const activities = await getActivities();
  const groups = Object.groupBy(activities, (x) => x.kategori);
  return <>
    <OriginalBanner breadcrumb="Ekstrakurikuler" label="Wadah Bakat & Minat" title="Ekstrakurikuler" description={`Lebih dari ${activities.length} kegiatan untuk mengembangkan bakat, minat, dan karakter siswa di luar jam pelajaran.`} />
    <div className="relative z-10 max-w-6xl mx-auto px-5 py-20 sm:py-24 space-y-20">{Object.entries(groups).map(([category, items]) => { const [icon, gradient] = meta[category] ?? ["✦", "from-leaf to-pine"]; return <section className="reveal" key={category}><div className="flex items-center gap-4 mb-8"><div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${gradient} flex items-center justify-center text-2xl shadow-lg`}>{icon}</div><div><h2 className="font-serif text-2xl sm:text-3xl text-pine dark:text-cream">{category}</h2><p className="text-xs text-pine/55 dark:text-cream/55">{items?.length} kegiatan</p></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{items?.map((item) => <div className="group rounded-2xl border border-pine/10 dark:border-cream/10 p-6 hover:border-brass hover:shadow-lg transition bg-cream-deep/40 dark:bg-pine/40" key={item.id}><div className="flex items-start gap-3"><span className="text-brass text-lg mt-0.5">✦</span><div><h3 className="font-serif text-lg text-pine dark:text-cream leading-snug mb-1.5 group-hover:text-leaf dark:group-hover:text-brass-light transition">{item.nama}</h3><p className="text-sm text-pine/70 dark:text-cream/70 leading-relaxed">{item.deskripsi}</p>{item.pembina && <p className="text-xs text-pine/50 dark:text-cream/50 mt-2">Pembina: {item.pembina}</p>}{item.jadwal && <p className="text-xs text-pine/50 dark:text-cream/50 mt-1">Jadwal: {item.jadwal}</p>}</div></div></div>)}</div></section>; })}</div>
    <section className="relative z-10 bg-pine text-cream"><div className="max-w-6xl mx-auto px-5 py-20 sm:py-24 grid md:grid-cols-3 gap-10"><div className="reveal"><p className="text-xs font-semibold tracking-widest text-brass-light uppercase mb-4">Informasi</p><h2 className="font-serif text-3xl leading-tight">Bagaimana cara bergabung?</h2></div><div className="md:col-span-2 reveal grid sm:grid-cols-3 gap-6">{[["01","Pilih Kegiatan","Pilih ekstrakurikuler sesuai minat dan bakatmu."],["02","Daftar","Isi formulir pendaftaran di awal tahun ajaran."],["03","Ikuti Jadwal","Hadir pada jadwal latihan rutin bersama pembina."]].map(([n,t,d]) => <div className="bg-pine-deep/60 rounded-2xl p-6 ring-1 ring-cream/10" key={n}><p className="numdot text-brass-light text-3xl mb-3">{n}</p><h3 className="font-serif text-lg mb-2">{t}</h3><p className="text-sm text-cream/70 leading-relaxed">{d}</p></div>)}</div></div></section>
    <OriginalCta title="Temukan bakatmu bersama kami." description="Jadilah bagian dari SMAS Putra Persada Batam dan kembangkan potensimu seluas-luasnya." />
  </>;
}
