import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BookOpen, HeartHandshake, Medal, ShieldCheck } from "lucide-react";
import { formatDate, getNews, getSettings, getTeachers, imageUrl, plainText } from "@/lib/data";

export default async function HomePage() {
  const [settings, news, teachers] = await Promise.all([getSettings(), getNews(4), getTeachers()]);
  return <>
    <section className="hero"><div className="container hero-grid">
      <div className="hero-copy"><span className="eyebrow">Sekolah Menengah Atas</span><h1>Menumbuhkan<br/><em>ilmu & akhlak</em><br/>yang berbuah.</h1><p>{settings.nama_sekolah} adalah ruang tumbuh bagi generasi cerdas dan berkarakter islami, siap melangkah menuju masa depan terbaik.</p><div className="actions"><Link className="button" href="/ppdb">Pendaftaran 2026/2027 <ArrowRight size={17}/></Link><Link className="button secondary" href="/tentang">Pelajari sekolah kami</Link></div></div>
      <div className="hero-art"><Image src="/assets/img/hero-ilustrasi.png" alt="Ilustrasi siswa belajar bersama" width={620} height={540} priority/><div className="hero-badge"><strong>{settings.tagline}</strong><br/><span>Belajar · Bertumbuh · Berbuah</span></div></div>
    </div></section>
    <section className="stats"><div className="container stats-grid"><div className="stat"><strong>{settings.akreditasi}</strong><span>{settings.label_akreditasi}</span></div><div className="stat"><strong>{settings.peserta_didik}</strong><span>{settings.label_peserta}</span></div><div className="stat"><strong>{settings.pengajar}</strong><span>{settings.label_pengajar}</span></div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Mengapa Kami</span><h2>Pendidikan yang utuh untuk masa depan.</h2></div><p>Kami menyatukan akademik, karakter, bakat, dan lingkungan belajar yang aman dalam satu pengalaman pendidikan.</p></div><div className="grid four">
      {[ [Medal,"Akademik Unggul","Kurikulum Merdeka dan bimbingan intensif menuju perguruan tinggi."], [ShieldCheck,"Karakter Islami","Pembiasaan ibadah, tahfiz, dan keteladanan akhlak mulia."], [BookOpen,"Bakat & Prestasi","Ekstrakurikuler dan pembinaan kompetisi sesuai potensi siswa."], [HeartHandshake,"Lingkungan Nyaman","Guru pendamping dan komunitas sekolah yang aman serta suportif."] ].map(([Icon,title,text])=><article className="card" key={title as string}><Icon size={30} color="var(--brass)"/><h3>{title as string}</h3><p>{text as string}</p></article>)}
    </div></div></section>
    <section className="section dark"><div className="container"><div className="section-head"><div><span className="eyebrow" style={{color:"var(--brass-light)"}}>Tenaga Pendidik</span><h2>Guru yang hadir untuk setiap langkah.</h2></div><Link href="/tentang">Kenali sekolah <ArrowRight size={16}/></Link></div><div className="grid four">{teachers.slice(0,4).map((teacher)=><article className="card teacher-card" key={teacher.id}><Image src={imageUrl(teacher.foto,"/assets/img/placeholder-guru.svg")} alt={teacher.nama} width={420} height={480}/><div><h3>{teacher.nama}</h3><p>{teacher.jabatan}</p></div></article>)}</div></div></section>
    <section className="section alt"><div className="container"><div className="section-head"><div><span className="eyebrow">Kabar Sekolah</span><h2>Berita & kegiatan terbaru.</h2></div><Link className="button secondary" href="/berita">Semua berita</Link></div><div className="grid three">{news.map((item,index)=><Link href={`/berita/${item.slug}`} className={`card news-card ${index===0?"news-feature":""}`} key={item.id}><span className="tag">{item.kategori}</span><div className="meta">{formatDate(item.tanggal)} · {item.dilihat} kali dilihat</div><h3>{item.judul}</h3><p>{plainText(item.isi).slice(0,index===0?220:120)}…</p><span className="read-more">Baca selengkapnya →</span></Link>)}</div></div></section>
    <section className="section"><div className="container card" style={{background:"var(--pine)",color:"white",padding:"clamp(2rem,6vw,5rem)",textAlign:"center"}}><span className="eyebrow" style={{color:"var(--brass-light)"}}>PPDB 2026/2027</span><h2>Mulai perjalanan terbaikmu bersama kami.</h2><p style={{color:"rgba(255,255,255,.7)",maxWidth:600,margin:"0 auto 1.5rem"}}>Temukan lingkungan belajar yang membantu setiap siswa tumbuh dengan ilmu, iman, dan keberanian.</p><Link className="button" href="/ppdb">Lihat informasi pendaftaran</Link></div></section>
  </>;
}
