-- Jalankan seluruh file ini melalui Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null default 'Pengguna',
  role text not null default 'viewer' check (role in ('admin','viewer')),
  created_at timestamptz not null default now()
);
create table if not exists public.pengaturan (id bigint generated by default as identity primary key,kunci text not null unique,nilai text not null);
create table if not exists public.berita (id bigint generated by default as identity primary key,judul text not null,slug text not null unique,kategori text not null,isi text not null,gambar text,tanggal date not null default current_date,dilihat integer not null default 0);
create table if not exists public.guru (id bigint generated by default as identity primary key,nama text not null,jabatan text not null,mapel text,foto text,urutan integer not null default 0);
create table if not exists public.ekstrakurikuler (id bigint generated by default as identity primary key,nama text not null,kategori text not null,deskripsi text not null,pembina text,jadwal text);
create table if not exists public.kategori_ekskul (id bigint generated by default as identity primary key,nama text not null unique,urutan integer not null default 0);
create table if not exists public.visi_misi (id bigint generated by default as identity primary key,tipe text not null check (tipe in ('visi','misi','tujuan','nilai')),judul text,isi text not null,urutan integer not null default 0);
create table if not exists public.tentang (id bigint generated by default as identity primary key,bagian text not null check (bagian in ('sejarah','sambutan','fasilitas')),judul text,isi text not null);
create table if not exists public.ppdb_info (id bigint generated by default as identity primary key,bagian text not null check (bagian in ('syarat','jadwal','alur','lokasi','faq')),judul text,isi text not null,tanggal text,file_formulir text,urutan integer not null default 0);
create table if not exists public.pesan_kontak (id bigint generated by default as identity primary key,nama text not null,email text not null,telepon text,subjek text,pesan text not null,tanggal timestamptz not null default now(),dibaca boolean not null default false);
create table if not exists public.audit_log (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete set null,action text not null,table_name text,record_id bigint,ip_address inet,created_at timestamptz not null default now());
create index if not exists berita_tanggal_idx on public.berita(tanggal desc);
create index if not exists guru_urutan_idx on public.guru(urutan);
create index if not exists pesan_tanggal_idx on public.pesan_kontak(tanggal desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,nama) values(new.id,coalesce(new.raw_user_meta_data->>'nama',split_part(new.email,'@',1))) on conflict(id) do nothing;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;

alter table public.profiles enable row level security;
alter table public.pengaturan enable row level security;
alter table public.berita enable row level security;
alter table public.guru enable row level security;
alter table public.ekstrakurikuler enable row level security;
alter table public.kategori_ekskul enable row level security;
alter table public.visi_misi enable row level security;
alter table public.tentang enable row level security;
alter table public.ppdb_info enable row level security;
alter table public.pesan_kontak enable row level security;
alter table public.audit_log enable row level security;

create policy "profile sendiri" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy "admin kelola profile" on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca pengaturan" on public.pengaturan for select to anon,authenticated using(true);
create policy "admin kelola pengaturan" on public.pengaturan for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca berita" on public.berita for select to anon,authenticated using(true);
create policy "admin kelola berita" on public.berita for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca guru" on public.guru for select to anon,authenticated using(true);
create policy "admin kelola guru" on public.guru for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca ekskul" on public.ekstrakurikuler for select to anon,authenticated using(true);
create policy "admin kelola ekskul" on public.ekstrakurikuler for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca kategori ekskul" on public.kategori_ekskul for select to anon,authenticated using(true);
create policy "admin kelola kategori ekskul" on public.kategori_ekskul for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca visi misi" on public.visi_misi for select to anon,authenticated using(true);
create policy "admin kelola visi misi" on public.visi_misi for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca tentang" on public.tentang for select to anon,authenticated using(true);
create policy "admin kelola tentang" on public.tentang for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik baca ppdb" on public.ppdb_info for select to anon,authenticated using(true);
create policy "admin kelola ppdb" on public.ppdb_info for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "publik kirim pesan" on public.pesan_kontak for insert to anon,authenticated with check(char_length(nama) between 2 and 100 and char_length(pesan) between 10 and 3000);
create policy "admin kelola pesan" on public.pesan_kontak for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin baca audit" on public.audit_log for select to authenticated using(public.is_admin());
create policy "admin tambah audit" on public.audit_log for insert to authenticated with check(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=excluded.public;
create policy "publik baca media" on storage.objects for select to anon,authenticated using(bucket_id='media');
create policy "admin unggah media" on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_admin());
create policy "admin ubah media" on storage.objects for update to authenticated using(bucket_id='media' and public.is_admin()) with check(bucket_id='media' and public.is_admin());
create policy "admin hapus media" on storage.objects for delete to authenticated using(bucket_id='media' and public.is_admin());

insert into public.pengaturan(kunci,nilai) values
('nama_sekolah','SMA Putra Persada Batam'),('tagline','Unggul & Berakhlak'),('akreditasi','B'),('label_akreditasi','Akreditasi'),('peserta_didik','750+'),('label_peserta','Peserta Didik'),('pengajar','45+'),('label_pengajar','Pengajar'),('alamat','Jl. Raya Persada, Batam Center, Kota Batam, Kepulauan Riau'),('telepon','(0778) XXX-XXXX'),('email','info@smaputrapersada.sch.id'),('jam_operasional','Senin–Jumat, 07.00–15.00 WIB'),('ppdb_status','buka') on conflict(kunci) do update set nilai=excluded.nilai;
insert into public.berita(judul,slug,kategori,isi,tanggal,dilihat) values
('Siswa Raih Emas Olimpiade Sains Provinsi Kepri','osn-emas','Prestasi','<p>Alhamdulillah, SMA Putra Persada Batam kembali meraih prestasi membanggakan.</p>','2026-06-12',245),
('Pentas Seni & Perpisahan Kelas XII Berlangsung Meriah','pentas-seni','Kegiatan','<p>Suasana haru bercampur bahagia menyelimuti acara pentas seni dan perpisahan kelas XII.</p>','2026-06-08',189),
('Shalat Dhuha & Tahfiz Rutin Setiap Pagi','shalat-dhuha','Keagamaan','<p>Pembinaan karakter islami dilakukan melalui shalat dhuha berjamaah dan tahfiz.</p>','2026-06-03',156) on conflict(slug) do nothing;
insert into public.guru(nama,jabatan,mapel,foto,urutan) values('Budi Santoso, M.Pd.','Kepala Sekolah','Manajemen Pendidikan','/assets/img/guru1.jpeg',1),('Siti Aminah, S.Pd.','Guru Matematika','Matematika','/assets/img/guru2.jpeg',2),('Ahmad Fauzi, M.Pd.','Guru Fisika','Fisika','/assets/img/guru3.jpeg',3),('Maya Kartika, S.Pd.','Guru Bahasa Inggris','Bahasa Inggris','/assets/img/guru4.jpeg',4);
insert into public.visi_misi(tipe,judul,isi,urutan) values('visi',null,'Mewujudkan generasi yang cerdas, berkarakter, beriman, dan berdaya saing global.',1),('misi',null,'Menyelenggarakan pembelajaran aktif, kreatif, dan berkualitas berbasis Kurikulum Merdeka.',1),('misi',null,'Membina karakter islami melalui pembiasaan ibadah, tahfiz, dan keteladanan akhlak mulia.',2),('nilai','Integritas','Menjunjung kejujuran dan tanggung jawab dalam segala hal.',1),('nilai','Peduli','Menumbuhkan empati terhadap sesama dan lingkungan.',2);
